### ISSUE TITLE
Flippers need to be bigger and work better

### ISSUE THREAD

**Issue by fragmental** [Double-Fine-Game-Club/pongball#147] opened 2017-04-28 03:16 UTC
The way they are now they don't really provide a lot of force and they are quite small.

I've been meaning to do this for a while.  They currently work with a hinge joint, but I had difficulty getting the hinge joint to provide significant force.  We might be able to bypass the lack of force by using our own custom force script, or by switching to a different method than hinge joint.

This is probably the next thing I plan on looking into.

**Comment by Cheeseness** [comment] 2017-04-29 02:40
Closing this as a duplicate of #127

**Closed as completed by Cheeseness** 2017-04-29 02:40 UTC
Labels: duplicate

**Comment by fragmental** [comment] 2017-04-29 04:39
Oh jeez.  My bad.
